### ISSUE TITLE
Does this project relate to any published paper?

### ISSUE THREAD

**Issue by xiangsheng1325** [INDElab/rgvae#1]
I guess your work is an implementation of this paper:
[Constrained Generation of Semantically Valid Graphs via Regularizing Variational Autoencoders](https://papers.nips.cc/paper/7942-constrained-generation-of-semantically-valid-graphs-via-regularizing-variational-autoencoders.pdf)

But there are some differences between code and thesis. Maybe you can write that in README.MD

Thanks.

**Comment by thiviyanT** [comment]
Thank you for your interest in our work!

We are not working on an implementation of the paper you mentioned. In our work, we are interested in generating novel Knowledge Graphs and tackle other research challenges. As soon as this work is complete, we will write a detailed README page that highlights what the differences are.
